{"ip": "110.148.145.223", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 1, in <module>\n    n = int(input(\"enter a number\"))\nValueError: invalid literal for int() with base 10: '\u753b'\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [4, 3, 2, 0, 17, "2-5"], "CorrectInputs": [[["999"], 1509788540], [["995"], 1509788557], [["495"], 1509788569], [["333"], 1509788581], [["200"], 1509788590], [["250"], 1509788603], [["300"], 1509788612], [["320"], 1509788624], [["325"], 1509788634], [["330"], 1509788643], [["332"], 1509788652]], "BadInput": ["\u753b"], "UniqueId": "c25a7503-3329-42e3-ed14-84549238c072_0", "TimeStamp": 1509788783}