{"ip": "2601:445:4101:4ad:c1a7:4339:e124:11d2", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 6, in <module>\n    convertbinary()\n  File \"temp2017.py\", line 3, in convertbinary\n    x = int(binarystring, 2)\nValueError: invalid literal for int() with base 2: \"'1110101\"\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [5, 1, 0, 0, 80, "4"], "CorrectInputs": [[["11111111"], 1487866900], [["1110101"], 1487866972]], "BadInput": ["'1110101"], "UniqueId": "c2f40b4e-492f-4dd4-edb9-21d174e46d2b_0", "TimeStamp": 1487866949}