{"ip": "4.28.70.34", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 24, in <module>\n    hanoi(number, start, goal, work)\n  File \"temp2017.py\", line 13, in hanoi\n    hanoi(n-1, start, work, goal)\n  File \"temp2017.py\", line 21, in hanoi\n    hanoi(n-1, work, goal, start)\n  File \"temp2017.py\", line 15, in hanoi\n    goal.append(start.pop())\nIndexError: pop from empty list\n", "LastIsEmpty": false, "ErrorType": "IndexError", "CoverageInfo": [17, 1, 6, 1, 91, "25,", "23->exit"], "CorrectInputs": [[["3 4"], 1505777236]], "BadInput": ["4 2"], "UniqueId": "c2ad8458-a21f-4310-a5bd-df5eec9660e6_2", "TimeStamp": 1505777284}