{"ip": "78.99.10.20", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 4, in <module>\n    a=int(input(\"Zadaj \u010d\u00edslo a 0 pre ukon\u010denie\"))\nValueError: invalid literal for int() with base 10: 'f'\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [28, 23, 12, 1, 15, "6,", "9-41,", "5->6"], "CorrectInputs": [[["4", "5", "2", "7", "7", "4"], 1511074354]], "BadInput": ["5", "6", "4", "8", "2", "3", "f"], "UniqueId": "c2e7ce47-aa4d-426d-832f-4ffc98d6b2c0_0", "TimeStamp": 1511074304}