{"ip": "189.35.185.52", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 2, in <module>\n    n1,n2,n3=elementos.split(' ')\nValueError: too many values to unpack (expected 3)\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [8, 6, 2, 0, 20, "3-9"], "CorrectInputs": [[["6.0 4.0 2.0"], 1508384342], [["6.0 4.0 2.1"], 1508384498]], "BadInput": [" 6.0 4.0 2.1"], "UniqueId": "c2508b9a-2e06-419d-fe8a-7fc840503dbd_1", "TimeStamp": 1508384379}