{"ip": "177.44.61.191", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 3, in <module>\n    m1,m2=map(str,input().split())\nValueError: not enough values to unpack (expected 2, got 0)\n", "LastIsEmpty": true, "ErrorType": "ValueError", "CoverageInfo": [6, 3, 4, 0, 30, "4-6"], "CorrectInputs": [[["6", "A B C D E F ", "C F"], 1486857816]], "BadInput": ["6", "A B C D E F", ""], "UniqueId": "c2d5f177-dfaf-4d90-a298-e7fdde8a3a9b_0", "TimeStamp": 1486857774}