{"ip": "189.35.185.52", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 2, in <module>\n    n1,n2,n3,n4=notas.split(' ')\nValueError: too many values to unpack (expected 4)\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [20, 18, 6, 0, 8, "3-22"], "CorrectInputs": [[["2.0 4.0 7.5 8.0", "6.4"], 1508380373], [["2.0 6.5 4.0 9.0"], 1508380434]], "BadInput": [" 2.0 6.5 4.0 9.0"], "UniqueId": "c2508b9a-2e06-419d-fe8a-7fc840503dbd_0", "TimeStamp": 1508380412}