{"ip": "2407:7000:962f:3671:dcf4:1af6:f112:4273", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 5, in <module>\n    while t[0] == \"n\":\nIndexError: string index out of range\n", "LastIsEmpty": false, "ErrorType": "IndexError", "CoverageInfo": [7, 0, 4, 1, 91, "4->exit"], "CorrectInputs": [[["1234567998"], 1503749151], [["123456798"], 1503749167], [["nnnnnnn"], 1503749543]], "BadInput": ["nnnnnnnnnnnnnnnnnn"], "UniqueId": "c2b55658-d8d6-4ce3-9497-da37e9535e9f_0", "TimeStamp": 1503749579}