{"ip": "85.89.112.179", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 1, in <module>\n    a=[int(i) for i in input().split()]\n  File \"temp2017.py\", line 1, in <listcomp>\n    a=[int(i) for i in input().split()]\nValueError: invalid literal for int() with base 10: 'a2'\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [2, 1, 2, 1, 50, "2,", "1->2"], "CorrectInputs": [[["1 2 3 4"], 1503498701]], "BadInput": [" 1 a2 3 4 b C"], "UniqueId": "c234f876-3f6b-4c82-dd3e-b4a8d9b1cf14_0", "TimeStamp": 1503498684}