{"ip": "178.206.32.244", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 2, in <module>\n    num=[int(input()) for i in range(n)]\n  File \"temp2017.py\", line 2, in <listcomp>\n    num=[int(input()) for i in range(n)]\nValueError: invalid literal for int() with base 10: ''\n", "LastIsEmpty": true, "ErrorType": "ValueError", "CoverageInfo": [6, 4, 6, 1, 25, "3-6,", "2->3"], "CorrectInputs": [[["3", "-1", "3", "7"], 1514265179]], "BadInput": ["3", "-1", ""], "UniqueId": "c278e117-b11f-46ad-c15a-0b01e46c1f05_0", "TimeStamp": 1514265146}