{"ip": "78.37.77.194", "ErrorMessage": "Traceback (most recent call last):\n  File \"temp2017.py\", line 1, in <module>\n    x = int(input(\"\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0442\u0443\u0440\u0430\u043b\u044c\u043d\u043e\u0435 \u0447\u0438\u0441\u043b\u043e: \"))\nValueError: invalid literal for int() with base 10: '20,2'\n", "LastIsEmpty": false, "ErrorType": "ValueError", "CoverageInfo": [7, 6, 2, 0, 11, "2-9"], "CorrectInputs": [[["20"], 1507217788]], "BadInput": ["20,2"], "UniqueId": "c2c4026d-dea0-489b-e719-30804af89291_0", "TimeStamp": 1507217846}